apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc-apijoev1
spec:
  environments:
    - name: development
    - name: test
    - name: production
  components:
    - name: radixquote
      src: "."
      ports:
        - name: http
          port: 3000
      public: true
      environmentVariables:
        - environment: development
          variables:
            PORT: 3000
        - environment: test
          variables:
            PORT: 3001
        - environment: prodiction
          variables:
            PORT: 3002